queue_rules:
  - name: default
    merge_method: merge
    merge_conditions: []

pull_request_rules:
  - name: queue on label
    conditions:
      - label=queue-me
    actions:
      queue:
        name: default
