pull_request_rules:
  - name: canary review as bot_account B
    conditions:
      - base=main
      - label=do-review
    actions:
      review:
        type: APPROVE
        message: "canary approval via bot_account"
        bot_account: louis-mgb-hunt
  - name: canary comment as bot_account B
    conditions:
      - base=main
      - label=do-comment
    actions:
      comment:
        message: "canary comment via bot_account"
        bot_account: louis-mgb-hunt
